version: '3'
services:
    charging_mongo:
        image: mongo:4.4
        ports:
            - 27018:27017
        networks:
            main:
        volumes:
            - ./charging-data:/data/db

    charging:
        image: charging-dev2
        links:
            - charging_mongo
        depends_on:
            - charging_mongo
        ports:
            - 8006:8006
        networks:
            main:
                aliases:
                    - charging.docker
        volumes:
            - ../src:/business-ecosystem-charging-backend/src/

networks:
    main:
        external: true
