name: Pre-Release

on:
  release:
    types: [prereleased]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get release tag
        id: get_release
        run: echo ::set-output name=RELEASE_TAG::${GITHUB_REF#refs/tags/}

      - uses: actions/checkout@v2

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: biz-ecosystem-charging-backend
          tags: ${{ github.sha }} ${{ steps.get_release.outputs.RELEASE_TAG }}
          dockerfiles: |
            ./docker/Dockerfile
          context: ./

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/fiware
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}