name: Trigger Testing Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  trigger-system-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repository Dispatch
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.ADMIN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          -d '{
            "event_type": "cross-repo-test",
            "client_payload": {
              "repository": "${{ github.repository }}",
              "branch": "${{ github.event.pull_request.head.ref }}",
              "pull_request_url": "${{ github.event.pull_request.html_url }}"
            }
          }' \
          https://api.github.com/repos/sluFicodes/DOME-testing/dispatches
