name: Tests

on:
  push:
    branches:
      - feat/extended-pricing

  pull_request:
    branches:
      - feat/extended-pricing

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          tags: |
            fiware/biz-ecosystem-charging-backend:10.0.0-rc2
          push: ${{ github.ref == 'refs/heads/feat/extended-pricing' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
