name: Tests

on:
  push:
    branches:
      - master
      - github-actions

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
      - run: pip install -r requirements.txt
      - run: pip install https://github.com/django-nonrel/django/archive/nonrel-1.6.zip 
      - run: pip install https://github.com/django-nonrel/djangotoolbox/archive/master.zip
      - run: pip install https://github.com/django-nonrel/mongodb-engine/archive/master.zip
      - run: pip install -r dev-requirements.txt
      - run: cd src/ && python manage.py test --noinput --with-xunit --nologcapture -v 2
